### ISSUE TITLE
this.items.add(elem) does not actually add elem to list of items

### ISSUE THREAD

**Issue by robinchow** [sapegin/jquery.mosaicflow#12]
Hi

Took me a while to figure out to Google down this path, but it seems that .add() constructs a new jQuery object, and does not modify the existing object you're adding to.  The end result is that if you're dynamically adding objects, and then resizing the window until you 'lose' a column, you actually lose all the items in that column.

I believe that line 233 should be changed to
```javascript
this.items = this.items.add(elm);
```
I've tested this and it fixes the issue of losing items.

**Comment by Sija** [comment]
Seems to by fixed by now.

**Comment by sapegin** [comment]
Can anyone else confirm?

**Comment by Sija** [comment]
In any case above mentioned line is gone.

**Comment by sapegin** [comment]
No code = no bug ;-)
