### ISSUE TITLE
Sane event names

### ISSUE THREAD

**Issue by sapegin** [sapegin/jquery.mosaicflow#33]
* mosaicflow-layout → layout.mosaicflow
* start → start.mosaicflow
* etc.

**Comment by Sija** [comment]
Hi, I'd like to take a stab at this issue. Event names used now were introduced in PR #20. By using so generic names they collide with `jQuery` own handlers - for instance `remove` (see PR #30). By prefixing them with `mosaicflow-` we'll avoid collisions like the one above. @sapegin how does it fly for ya?

**Comment by sapegin** [comment]
Sounds good for me.
