### ISSUE TITLE
Set the number of columns instead?

### ISSUE THREAD

**Issue by withlovee** [sapegin/jquery.mosaicflow#40]
I don't want to set the minimum width, but I would like to always have a 2-column grid. Is it possible to have that? Thanks!

**Comment by raulferras** [comment]
Maybe I'm missing something but if you want a fixed number of columns then
I don't think you need this plugin at all. Specifying two columns on your
CSS will suffice.

**Comment by Sija** [comment]
Looks like this issue have been resolved, closing.
