### ISSUE TITLE
clearfix class

### ISSUE THREAD

**Issue by chrisemory** [sapegin/jquery.mosaicflow#41]
In your html you use a **clearfix** class on the top div (see below), but your example css does not have a **clearfix** item. I was wondering what **clearfix** css were you using? 

Thank you

`<div class="clearfix mosaicflow">`

**Comment by sapegin** [comment]
You can use any clearfix you like. I use [one from my framework](https://github.com/tamiadev/tamia/blob/master/tamia/misc.styl#L70-L77).
