### ISSUE TITLE
Rebuild Gallery Trigger

### ISSUE THREAD

**Issue by craigmroberts** [sapegin/jquery.mosaicflow#44]
Hi, is it currently possible to rebuild the gallery after it has been built?
Basically I have a gallery with items that have been starred I want to remove the items but it is leaving empty columns and the items aren't evenly stacked.

So I was wondering when the items are removed. Id like a rebuild gallery columns feature?

Thanks,
- Craig

**Comment by sapegin** [comment]
Did you use `remove` method?

**Comment by craigmroberts** [comment]
I did but I kept getting a jQuery error (below) when resizing the window.
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined.

I think I'm just going to go with the option of creating a separate gallery and hide and show it instead. But obviously would rather a rebuild option for convenience.

**Comment by Sija** [comment]
Should be fixed by #48.
